// Serie A listone classic - imported from the league's own export
// (lista_calciatori_classic). Players flagged 'Fuori lista' are excluded.
// Shape: [name, role, club, quotazione]. P portiere, D difensore, C centrocampista, A attaccante.
// Names are already unique in the source, using its own disambiguation
// (Martinez L. / Martinez Jo.), which is what the no-duplicate rule matches on.
// To refresh: replace this array. Nothing else needs to change.

const RAW = [
  ["Svilar", "P", "Roma", 19],
  ["Carnesecchi", "P", "Atalanta", 17],
  ["Martinez Jo.", "P", "Inter", 17],
  ["Vicario", "P", "Juventus", 17],
  ["Butez", "P", "Como", 15],
  ["Maignan", "P", "Milan", 15],
  ["De Gea", "P", "Fiorentina", 11],
  ["Meret", "P", "Napoli", 11],
  ["Caprile", "P", "Cagliari", 10],
  ["Mandas", "P", "Lazio", 10],
  ["Skorupski", "P", "Bologna", 10],
  ["Okoye", "P", "Udinese", 9],
  ["Perri", "P", "Torino", 9],
  ["Bijlow", "P", "Genoa", 8],
  ["Falcone", "P", "Lecce", 8],
  ["Sanchez Ro.", "P", "Como", 8],
  ["Muric", "P", "Sassuolo", 7],
  ["Daffara", "P", "Parma", 6],
  ["Stankovic F.", "P", "Venezia", 6],
  ["Milinkovic-Savic V.", "P", "Napoli", 5],
  ["Palmisani", "P", "Frosinone", 5],
  ["Thiam", "P", "Monza", 4],
  ["Corvi", "P", "Parma", 2],
  ["Desplanches", "P", "Frosinone", 2],
  ["Provedel", "P", "Inter", 2],
  ["Bleve", "P", "Lecce", 1],
  ["Christensen O.", "P", "Fiorentina", 1],
  ["Contini", "P", "Napoli", 1],
  ["De Marzi", "P", "Roma", 1],
  ["Di Gennaro", "P", "Inter", 1],
  ["Ghidotti", "P", "Parma", 1],
  ["Gollini", "P", "Roma", 1],
  ["Grabara", "P", "Juventus", 1],
  ["Grandi", "P", "Venezia", 1],
  ["Happonen", "P", "Bologna", 1],
  ["Lezzerini", "P", "Fiorentina", 1],
  ["Lolic", "P", "Frosinone", 1],
  ["Mascardi", "P", "Torino", 1],
  ["Montipò", "P", "Venezia", 1],
  ["Motta", "P", "Lazio", 1],
  ["Mrozek", "P", "Udinese", 1],
  ["Padelli", "P", "Udinese", 1],
  ["Paleari", "P", "Torino", 1],
  ["Penev", "P", "Lecce", 1],
  ["Pessina Mas.", "P", "Bologna", 1],
  ["Piana", "P", "Udinese", 1],
  ["Pinsoglio", "P", "Juventus", 1],
  ["Pisseri", "P", "Frosinone", 1],
  ["Pompei", "P", "Atalanta", 1],
  ["Pozzi", "P", "Venezia", 1],
  ["Radunovic", "P", "Cagliari", 1],
  ["Renzetti", "P", "Lazio", 1],
  ["Russo A.", "P", "Sassuolo", 1],
  ["Satalino", "P", "Sassuolo", 1],
  ["Sherri", "P", "Cagliari", 1],
  ["Siviero", "P", "Torino", 1],
  ["Sommariva", "P", "Genoa", 1],
  ["Sportiello", "P", "Atalanta", 1],
  ["Stolz", "P", "Genoa", 1],
  ["Strajnar", "P", "Monza", 1],
  ["Terracciano", "P", "Milan", 1],
  ["Tornqvist", "P", "Monza", 1],
  ["Torriani", "P", "Milan", 1],
  ["Turati", "P", "Sassuolo", 1],
  ["Vigorito", "P", "Como", 1],
  ["Dimarco", "D", "Inter", 31],
  ["Molina N.", "D", "Roma", 18],
  ["Wesley", "D", "Roma", 18],
  ["Bremer", "D", "Juventus", 16],
  ["Mancini", "D", "Roma", 16],
  ["Akanji", "D", "Inter", 15],
  ["Rrahmani", "D", "Napoli", 15],
  ["Bastoni", "D", "Inter", 14],
  ["Kalulu", "D", "Juventus", 14],
  ["Pavlovic", "D", "Milan", 14],
  ["Gila", "D", "Milan", 13],
  ["N'Dicka", "D", "Roma", 13],
  ["Solet", "D", "Udinese", 13],
  ["Bisseck", "D", "Inter", 12],
  ["Di Lorenzo", "D", "Napoli", 12],
  ["Stones", "D", "Inter", 12],
  ["Hermoso", "D", "Roma", 11],
  ["Ostigard", "D", "Genoa", 11],
  ["Spence", "D", "Inter", 11],
  ["Chalobah T.", "D", "Como", 10],
  ["Ramon", "D", "Como", 10],
  ["Scalvini", "D", "Atalanta", 10],
  ["Dodò", "D", "Fiorentina", 9],
  ["Kamara H.", "D", "Udinese", 9],
  ["Vasquez", "D", "Genoa", 9],
  ["Vojvoda", "D", "Udinese", 9],
  ["Bartesaghi", "D", "Milan", 8],
  ["Cambiaso", "D", "Juventus", 8],
  ["Celik", "D", "Juventus", 8],
  ["Comuzzo", "D", "Torino", 8],
  ["Couto", "D", "Como", 8],
  ["Delprato", "D", "Parma", 8],
  ["Diego Carlos", "D", "Parma", 8],
  ["Doekhi", "D", "Lazio", 8],
  ["Koulierakis", "D", "Roma", 8],
  ["Miranda J.", "D", "Bologna", 8],
  ["Spinazzola", "D", "Napoli", 8],
  ["Theate", "D", "Bologna", 8],
  ["Tiago Gabriel", "D", "Lecce", 8],
  ["Valeri", "D", "Parma", 8],
  ["Zappacosta", "D", "Atalanta", 8],
  ["Badiashile", "D", "Napoli", 7],
  ["Belghali", "D", "Torino", 7],
  ["Bracaglia", "D", "Frosinone", 7],
  ["Coco", "D", "Torino", 7],
  ["Dragusin", "D", "Fiorentina", 7],
  ["Gabbia", "D", "Milan", 7],
  ["Hien", "D", "Atalanta", 7],
  ["Idzes", "D", "Sassuolo", 7],
  ["Ismajli", "D", "Torino", 7],
  ["Jimenez A.", "D", "Fiorentina", 7],
  ["Lucumì", "D", "Juventus", 7],
  ["Mangas", "D", "Monza", 7],
  ["Mina", "D", "Cagliari", 7],
  ["Obert", "D", "Cagliari", 7],
  ["Sutalo J.", "D", "Lazio", 7],
  ["Tavares N.", "D", "Lazio", 7],
  ["Zortea", "D", "Bologna", 7],
  ["Balerdi", "D", "Roma", 6],
  ["Bellanova", "D", "Atalanta", 6],
  ["Bernasconi", "D", "Atalanta", 6],
  ["Beukema", "D", "Napoli", 6],
  ["Buongiorno", "D", "Napoli", 6],
  ["Caleta-Car", "D", "Sassuolo", 6],
  ["Carlos Augusto", "D", "Inter", 6],
  ["Fortini", "D", "Torino", 6],
  ["Gallo", "D", "Lecce", 6],
  ["Heggem", "D", "Bologna", 6],
  ["Holm", "D", "Bologna", 6],
  ["Kaiki", "D", "Como", 6],
  ["Kolasinac", "D", "Atalanta", 6],
  ["Kristensen T.", "D", "Atalanta", 6],
  ["Leysen F.", "D", "Sassuolo", 6],
  ["Marcandalli", "D", "Genoa", 6],
  ["Marusic", "D", "Lazio", 6],
  ["Monterisi", "D", "Frosinone", 6],
  ["Obrador", "D", "Sassuolo", 6],
  ["Oyono A.", "D", "Frosinone", 6],
  ["Pavard", "D", "Inter", 6],
  ["Pedraza", "D", "Lazio", 6],
  ["Romagnoli", "D", "Lazio", 6],
  ["Sugawara", "D", "Cagliari", 6],
  ["Tomori", "D", "Milan", 6],
  ["Valle", "D", "Como", 6],
  ["Veiga D.", "D", "Lecce", 6],
  ["Viery", "D", "Fiorentina", 6],
  ["Bella-Kotchap", "D", "Venezia", 5],
  ["Calvani", "D", "Frosinone", 5],
  ["Correia T.", "D", "Venezia", 5],
  ["De Winter", "D", "Milan", 5],
  ["Doig", "D", "Sassuolo", 5],
  ["Gaspar K.", "D", "Lecce", 5],
  ["Ghilardi", "D", "Roma", 5],
  ["Haps", "D", "Venezia", 5],
  ["Kelly L.", "D", "Juventus", 5],
  ["Kempf", "D", "Como", 5],
  ["Kofler", "D", "Cagliari", 5],
  ["Olivera", "D", "Napoli", 5],
  ["Patterson", "D", "Torino", 5],
  ["Valdepenas", "D", "Fiorentina", 5],
  ["Zè Pedro", "D", "Cagliari", 5],
  ["Arizala", "D", "Udinese", 4],
  ["Bertola", "D", "Udinese", 4],
  ["Birindelli", "D", "Monza", 4],
  ["Cittadini", "D", "Frosinone", 4],
  ["Comert", "D", "Torino", 4],
  ["Favasuli", "D", "Napoli", 4],
  ["Floriani Mussolini", "D", "Lazio", 4],
  ["Gatti", "D", "Juventus", 4],
  ["Hainaut", "D", "Venezia", 4],
  ["Juan Jesus", "D", "Venezia", 4],
  ["Kabasele", "D", "Udinese", 4],
  ["Kossounou", "D", "Atalanta", 4],
  ["Mitaj", "D", "Genoa", 4],
  ["Moreno M.", "D", "Venezia", 4],
  ["Parisi", "D", "Fiorentina", 4],
  ["Pongracic", "D", "Fiorentina", 4],
  ["Provstgaard", "D", "Lazio", 4],
  ["Rensch", "D", "Roma", 4],
  ["Rodriguez Ju.", "D", "Cagliari", 4],
  ["Siebert", "D", "Lecce", 4],
  ["Smolcic I.", "D", "Como", 4],
  ["Terzic", "D", "Frosinone", 4],
  ["Valenti", "D", "Parma", 4],
  ["Vitik", "D", "Bologna", 4],
  ["Walukiewicz", "D", "Sassuolo", 4],
  ["Zanoli", "D", "Udinese", 4],
  ["Akpoguma", "D", "Frosinone", 3],
  ["Britschgi", "D", "Parma", 3],
  ["Candè", "D", "Sassuolo", 3],
  ["Carboni A.", "D", "Monza", 3],
  ["Casale", "D", "Bologna", 3],
  ["Drameh", "D", "Genoa", 3],
  ["Ebosse", "D", "Udinese", 3],
  ["Estupinan", "D", "Milan", 3],
  ["Franjic", "D", "Venezia", 3],
  ["Halhal", "D", "Venezia", 3],
  ["Helland", "D", "Bologna", 3],
  ["Idrissi R.", "D", "Cagliari", 3],
  ["Joao Mario", "D", "Fiorentina", 3],
  ["Kambwala", "D", "Como", 3],
  ["Kouadio", "D", "Monza", 3],
  ["Lucchesi", "D", "Monza", 3],
  ["Odenthal", "D", "Sassuolo", 3],
  ["Palma", "D", "Udinese", 3],
  ["Ranieri L.", "D", "Fiorentina", 3],
  ["Schingtienne", "D", "Venezia", 3],
  ["Sverko", "D", "Venezia", 3],
  ["Tchato", "D", "Frosinone", 3],
  ["Troilo", "D", "Parma", 3],
  ["Abankwah", "D", "Udinese", 2],
  ["Alhassane", "D", "Bologna", 2],
  ["Aurelio", "D", "Cagliari", 2],
  ["Bakoune", "D", "Monza", 2],
  ["Biraghi", "D", "Torino", 2],
  ["Cinquegrano", "D", "Sassuolo", 2],
  ["Diawara S.", "D", "Milan", 2],
  ["Drobnic", "D", "Parma", 2],
  ["Goglichidze", "D", "Monza", 2],
  ["Jean", "D", "Lecce", 2],
  ["Lazzari", "D", "Lazio", 2],
  ["Lulli", "D", "Roma", 2],
  ["Marin R.", "D", "Napoli", 2],
  ["Ndaba", "D", "Lecce", 2],
  ["Ndiaye", "D", "Parma", 2],
  ["Otoa", "D", "Genoa", 2],
  ["Pellegrini Lu.", "D", "Lazio", 2],
  ["Puczka", "D", "Genoa", 2],
  ["Sabelli", "D", "Genoa", 2],
  ["Sagrado", "D", "Venezia", 2],
  ["Terracciano F.", "D", "Milan", 2],
  ["Van Der Brempt", "D", "Sassuolo", 2],
  ["Amey", "D", "Frosinone", 1],
  ["Antov", "D", "Monza", 1],
  ["Cabal", "D", "Juventus", 1],
  ["Carboni F.", "D", "Parma", 1],
  ["De Silvestri", "D", "Bologna", 1],
  ["Dembelè A.", "D", "Lecce", 1],
  ["Goldaniga", "D", "Como", 1],
  ["Gomes", "D", "Venezia", 1],
  ["Marianucci", "D", "Napoli", 1],
  ["Maye", "D", "Monza", 1],
  ["Mazzocchi", "D", "Venezia", 1],
  ["Omar Fayed", "D", "Frosinone", 1],
  ["Patric", "D", "Lazio", 1],
  ["Pieragnolo", "D", "Sassuolo", 1],
  ["Rugani", "D", "Juventus", 1],
  ["Ziolkowski", "D", "Monza", 1],
  ["Paz N.", "C", "Como", 29],
  ["Calhanoglu", "C", "Inter", 28],
  ["McTominay", "C", "Napoli", 27],
  ["Orsolini", "C", "Bologna", 25],
  ["Pulisic", "C", "Milan", 24],
  ["Rabiot", "C", "Milan", 23],
  ["Baturina", "C", "Como", 20],
  ["Mora", "C", "Roma", 20],
  ["Barella", "C", "Inter", 18],
  ["Da Cunha", "C", "Como", 18],
  ["Zaniolo", "C", "Udinese", 18],
  ["De Bruyne", "C", "Napoli", 17],
  ["McKennie", "C", "Juventus", 17],
  ["Zaccagni", "C", "Lazio", 16],
  ["Atta", "C", "Fiorentina", 15],
  ["Conceicao", "C", "Juventus", 13],
  ["Samardzic", "C", "Atalanta", 13],
  ["Taylor K.", "C", "Lazio", 13],
  ["Vlasic", "C", "Torino", 13],
  ["Ederson D.S.", "C", "Atalanta", 12],
  ["Ekkelenkamp", "C", "Udinese", 12],
  ["Goncalves P.", "C", "Fiorentina", 12],
  ["Gonzalez N.", "C", "Juventus", 12],
  ["Gudmundsson A.", "C", "Lazio", 12],
  ["Jones C.", "C", "Inter", 12],
  ["Kessiè", "C", "Atalanta", 12],
  ["Modric", "C", "Milan", 12],
  ["Zielinski", "C", "Inter", 12],
  ["Alajbegovic", "C", "Juventus", 11],
  ["Baldanzi", "C", "Genoa", 11],
  ["Mastantuono", "C", "Fiorentina", 11],
  ["Moreira", "C", "Milan", 11],
  ["Rodriguez Je.", "C", "Como", 11],
  ["Saelemaekers", "C", "Milan", 11],
  ["Bernardeschi", "C", "Bologna", 10],
  ["Frattesi", "C", "Lazio", 10],
  ["Konè M.", "C", "Roma", 10],
  ["Perrone", "C", "Como", 10],
  ["Rowe", "C", "Atalanta", 10],
  ["Thorstvedt", "C", "Sassuolo", 10],
  ["Vergara", "C", "Napoli", 10],
  ["Zambo Anguissa", "C", "Napoli", 10],
  ["Cancellieri", "C", "Lazio", 9],
  ["Casadei", "C", "Torino", 9],
  ["Colpani", "C", "Monza", 9],
  ["Cristante", "C", "Roma", 9],
  ["Diouf", "C", "Inter", 9],
  ["Isaksen", "C", "Lazio", 9],
  ["Locatelli", "C", "Juventus", 9],
  ["Pellegrini Lo.", "C", "Roma", 9],
  ["Politano", "C", "Napoli", 9],
  ["Sucic P.", "C", "Inter", 9],
  ["Thuram K.", "C", "Juventus", 9],
  ["Volpato", "C", "Sassuolo", 9],
  ["Calò", "C", "Frosinone", 8],
  ["Cambiaghi", "C", "Bologna", 8],
  ["Chukwueze", "C", "Milan", 8],
  ["Hutchinson", "C", "Milan", 8],
  ["Konè I.", "C", "Sassuolo", 8],
  ["Lobotka", "C", "Napoli", 8],
  ["Mandragora", "C", "Torino", 8],
  ["Mbangula", "C", "Bologna", 8],
  ["Odgaard", "C", "Bologna", 8],
  ["Pasalic", "C", "Atalanta", 8],
  ["Schmid", "C", "Frosinone", 8],
  ["Adopo", "C", "Cagliari", 7],
  ["Akinsanmiro", "C", "Monza", 7],
  ["Bernabè", "C", "Parma", 7],
  ["Coulibaly L.", "C", "Lecce", 7],
  ["El Shaarawy", "C", "Genoa", 7],
  ["Elmas", "C", "Atalanta", 7],
  ["Fagioli", "C", "Fiorentina", 7],
  ["Ferguson", "C", "Bologna", 7],
  ["Frendrup", "C", "Genoa", 7],
  ["Gaetano", "C", "Atalanta", 7],
  ["Karlstrom", "C", "Udinese", 7],
  ["Koopmeiners", "C", "Juventus", 7],
  ["Monteiro J.", "C", "Lecce", 7],
  ["Ndour", "C", "Fiorentina", 7],
  ["Pisilli", "C", "Roma", 7],
  ["Romano", "C", "Cagliari", 7],
  ["Rovella", "C", "Lazio", 7],
  ["Sarr P.", "C", "Juventus", 7],
  ["Sow", "C", "Genoa", 7],
  ["Unai Gomez", "C", "Udinese", 7],
  ["Zalewski", "C", "Atalanta", 7],
  ["Adzic", "C", "Sassuolo", 6],
  ["Bakola", "C", "Sassuolo", 6],
  ["Basic", "C", "Venezia", 6],
  ["Braganca", "C", "Torino", 6],
  ["Cacciamani", "C", "Torino", 6],
  ["Caqueret", "C", "Como", 6],
  ["Ellertsson", "C", "Genoa", 6],
  ["Fazzini", "C", "Cagliari", 6],
  ["Liberali", "C", "Como", 6],
  ["Matic", "C", "Sassuolo", 6],
  ["Milla", "C", "Como", 6],
  ["Nicolussi Caviglia", "C", "Parma", 6],
  ["Oristanio", "C", "Torino", 6],
  ["Oulai", "C", "Fiorentina", 6],
  ["Pessina", "C", "Monza", 6],
  ["Pierotti", "C", "Lecce", 6],
  ["Piotrowski", "C", "Udinese", 6],
  ["Pobega", "C", "Bologna", 6],
  ["Tourè I.", "C", "Monza", 6],
  ["Winks", "C", "Cagliari", 6],
  ["Zerbin", "C", "Frosinone", 6],
  ["Zhegrova", "C", "Juventus", 6],
  ["Amondarain", "C", "Bologna", 5],
  ["Busio", "C", "Venezia", 5],
  ["Cissè A.", "C", "Milan", 5],
  ["Dele-Bashiru", "C", "Lazio", 5],
  ["Felici", "C", "Cagliari", 5],
  ["Fitz-Jim", "C", "Torino", 5],
  ["Gineitis", "C", "Torino", 5],
  ["Jashari", "C", "Milan", 5],
  ["Keita M.", "C", "Parma", 5],
  ["Luis Henrique", "C", "Inter", 5],
  ["Meichtry", "C", "Genoa", 5],
  ["Perez K.", "C", "Venezia", 5],
  ["Sohm", "C", "Venezia", 5],
  ["Addai", "C", "Como", 4],
  ["Almqvist", "C", "Parma", 4],
  ["Amorim", "C", "Genoa", 4],
  ["Berisha M.", "C", "Lecce", 4],
  ["Cataldi", "C", "Lazio", 4],
  ["Cichella", "C", "Frosinone", 4],
  ["De Roon", "C", "Roma", 4],
  ["Dominguez B.", "C", "Sassuolo", 4],
  ["Douglas Luiz", "C", "Juventus", 4],
  ["Fabbian", "C", "Parma", 4],
  ["Fini", "C", "Frosinone", 4],
  ["Folorunsho", "C", "Monza", 4],
  ["Gandelman", "C", "Lecce", 4],
  ["Grillitsch", "C", "Frosinone", 4],
  ["Ilkhan", "C", "Torino", 4],
  ["Koutsoupias", "C", "Frosinone", 4],
  ["Loftus-Cheek", "C", "Milan", 4],
  ["Massolin", "C", "Cagliari", 4],
  ["Messias", "C", "Genoa", 4],
  ["Miller L.", "C", "Udinese", 4],
  ["Mkhitaryan", "C", "Inter", 4],
  ["Moro N.", "C", "Bologna", 4],
  ["Ngom", "C", "Lecce", 4],
  ["Njie", "C", "Fiorentina", 4],
  ["Ricci S.", "C", "Como", 4],
  ["Traorè Hj.", "C", "Genoa", 4],
  ["Aboukhlal", "C", "Torino", 3],
  ["Brescianini", "C", "Fiorentina", 3],
  ["Colombo L.", "C", "Monza", 3],
  ["Deiola", "C", "Cagliari", 3],
  ["Diallo O.", "C", "Parma", 3],
  ["Fernandez T.", "C", "Venezia", 3],
  ["Gagliardini", "C", "Cagliari", 3],
  ["Gelli F.", "C", "Frosinone", 3],
  ["Gilmour", "C", "Napoli", 3],
  ["Gorter", "C", "Lecce", 3],
  ["Helgason", "C", "Venezia", 3],
  ["Maleh", "C", "Lecce", 3],
  ["Masini", "C", "Frosinone", 3],
  ["Musah", "C", "Milan", 3],
  ["Ordonez C.", "C", "Parma", 3],
  ["Stankovic A.", "C", "Inter", 3],
  ["Sulemana I.", "C", "Sassuolo", 3],
  ["Belahyane", "C", "Lazio", 2],
  ["Boloca", "C", "Sassuolo", 2],
  ["Chakvetadze", "C", "Udinese", 2],
  ["Ciurria", "C", "Monza", 2],
  ["Cremaschi", "C", "Parma", 2],
  ["Duncan", "C", "Venezia", 2],
  ["El Azzouzi O.", "C", "Bologna", 2],
  ["Fadera", "C", "Cagliari", 2],
  ["Foe Ondoa", "C", "Monza", 2],
  ["Forson O.", "C", "Monza", 2],
  ["Hasa", "C", "Frosinone", 2],
  ["Jovanovic", "C", "Udinese", 2],
  ["Lipani", "C", "Sassuolo", 2],
  ["Venturino", "C", "Genoa", 2],
  ["Zarraga", "C", "Udinese", 2],
  ["Anjorin", "C", "Torino", 1],
  ["Ciervo", "C", "Cagliari", 1],
  ["Comotto", "C", "Milan", 1],
  ["Dagasso", "C", "Venezia", 1],
  ["El Azzouzi A.", "C", "Frosinone", 1],
  ["Fofana Sa.", "C", "Lecce", 1],
  ["Ilic", "C", "Lecce", 1],
  ["Kaba", "C", "Lecce", 1],
  ["Kone B.", "C", "Frosinone", 1],
  ["Laerke", "C", "Lecce", 1],
  ["Lahdo", "C", "Como", 1],
  ["Liteta", "C", "Cagliari", 1],
  ["Mout", "C", "Monza", 1],
  ["Przyborek", "C", "Lazio", 1],
  ["Malen", "A", "Roma", 38],
  ["Martinez L.", "A", "Inter", 33],
  ["Hojlund", "A", "Napoli", 28],
  ["Thuram", "A", "Inter", 28],
  ["Ramos G.", "A", "Milan", 27],
  ["Kolo Muani", "A", "Juventus", 25],
  ["Kean", "A", "Como", 24],
  ["Woltemade", "A", "Juventus", 23],
  ["Douvikas", "A", "Como", 22],
  ["Yildiz", "A", "Juventus", 22],
  ["Berardi", "A", "Sassuolo", 19],
  ["Davis K.", "A", "Udinese", 19],
  ["Scamacca", "A", "Atalanta", 19],
  ["Krstovic", "A", "Atalanta", 18],
  ["De Ketelaere", "A", "Atalanta", 17],
  ["Esposito F.P.", "A", "Inter", 17],
  ["Dybala", "A", "Roma", 16],
  ["Dovbyk", "A", "Bologna", 15],
  ["Laurientè", "A", "Sassuolo", 15],
  ["Beto", "A", "Fiorentina", 14],
  ["Castro S.", "A", "Roma", 14],
  ["Pellegrino M.", "A", "Fiorentina", 14],
  ["Raspadori", "A", "Atalanta", 14],
  ["Santos A.", "A", "Napoli", 14],
  ["Simeone", "A", "Torino", 14],
  ["Soulè", "A", "Roma", 13],
  ["Diao", "A", "Como", 12],
  ["Esposito Se.", "A", "Sassuolo", 12],
  ["Kevin Carlos", "A", "Cagliari", 12],
  ["Pinamonti", "A", "Lazio", 12],
  ["Adams A.", "A", "Venezia", 11],
  ["Colombo", "A", "Genoa", 11],
  ["Adams C.", "A", "Torino", 10],
  ["Romero D.", "A", "Parma", 10],
  ["Tourè E.", "A", "Parma", 10],
  ["Bobcek", "A", "Frosinone", 9],
  ["Bowie", "A", "Sassuolo", 9],
  ["Cutrone", "A", "Monza", 9],
  ["Raimondo", "A", "Frosinone", 9],
  ["Yeboah J.", "A", "Venezia", 9],
  ["Geubbels", "A", "Lecce", 8],
  ["Ghedjemis", "A", "Frosinone", 8],
  ["Osmajic", "A", "Genoa", 8],
  ["Piccoli", "A", "Bologna", 8],
  ["Vitinha O.", "A", "Genoa", 8],
  ["Boga", "A", "Juventus", 7],
  ["Bonny", "A", "Inter", 7],
  ["Gnonto", "A", "Fiorentina", 7],
  ["Rrahmani Al.", "A", "Venezia", 7],
  ["Varela G.", "A", "Monza", 7],
  ["Kvernadze", "A", "Frosinone", 6],
  ["Neres", "A", "Napoli", 6],
  ["Noslin", "A", "Lazio", 6],
  ["Stulic", "A", "Lecce", 6],
  ["Sulemana K.", "A", "Atalanta", 6],
  ["Zapata D.", "A", "Torino", 6],
  ["Zeballos", "A", "Monza", 6],
  ["Birligea", "A", "Frosinone", 5],
  ["Maldini", "A", "Cagliari", 5],
  ["Ngonge", "A", "Monza", 5],
  ["Adorante", "A", "Venezia", 4],
  ["Borrelli", "A", "Cagliari", 4],
  ["Camarda", "A", "Milan", 4],
  ["Fatah", "A", "Lecce", 4],
  ["Frigan", "A", "Parma", 4],
  ["Giovane", "A", "Napoli", 4],
  ["Gueye", "A", "Udinese", 4],
  ["Havel", "A", "Genoa", 4],
  ["Kulenovic", "A", "Torino", 4],
  ["Lang", "A", "Napoli", 4],
  ["Lucca", "A", "Napoli", 4],
  ["Mendy P.", "A", "Cagliari", 4],
  ["Milik", "A", "Juventus", 4],
  ["Mota", "A", "Monza", 4],
  ["N'Dri", "A", "Lecce", 4],
  ["Nzola", "A", "Cagliari", 4],
  ["Robinson J.", "A", "Monza", 4],
  ["Ekhator", "A", "Juventus", 3],
  ["Elphege", "A", "Parma", 3],
  ["Lontani", "A", "Parma", 3],
  ["Enem", "A", "Bologna", 2],
  ["Bayo V.", "A", "Udinese", 1],
  ["De Martis", "A", "Parma", 1],
  ["Lauberbach", "A", "Venezia", 1],
  ["Lisman", "A", "Venezia", 1],
  ["Robinho Junior", "A", "Genoa", 1],
  ["Trepy", "A", "Cagliari", 1]
];

export const PLAYERS = RAW.map(([name, role, club, q]) => ({ name, role, club, q }));

// strip accents, punctuation and case so "dallinga" finds "D'Allinga" and "paz" finds "Paz N."
export const fold = (s) =>
  (s || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/['`.\-()]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();

const INDEX = PLAYERS.map((p) => ({ ...p, folded: fold(p.name) }));

// Suggestions for the admin box: right role, not already sold, dearest first.
export function searchPlayers(query, role, takenFolded, limit = 8) {
  const q = fold(query);
  const pool = INDEX.filter((p) => p.role === role && !takenFolded.has(p.folded));
  if (!q) return pool.slice(0, limit);

  const starts = [];
  const contains = [];
  for (const p of pool) {
    const i = p.folded.indexOf(q);
    if (i === 0 || p.folded.includes(" " + q)) starts.push(p);
    else if (i > 0) contains.push(p);
  }
  return [...starts, ...contains].slice(0, limit);
}

export const isKnownPlayer = (name, role) => {
  const f = fold(name);
  return INDEX.some((p) => p.folded === f && p.role === role);
};
